language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"
env:
  - REPO_NAME=boxes-scroll
branches:
  only:
  - website
before_install:
  - sudo apt-get install lftp
before_script:
  - rm -rf node_modules/boxes-scroll
  - npm install
script: 
  - webpack
deploy:
  - provider: script
    script: ls public_html; lftp sftp://$SFTP_1AND1_HOST -u $SFTP_1AND1_USER,$SFTP_1AND1_PWD -e "lcd public_html; cd $REPO_NAME; mrm **/*; mirror -e -R; bye"
    skip_cleanup: true
    on:
      branch: website
